{% set name = "FrictionQPotSpringBlock" %}
{% set version = "0.3.2" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 85e2eef5849360dac69f4248ff15f0f717fe46fa312d05174b8b054d3b64d71a

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - setuptools_scm
    - pip
    - pyxtensor
    - qpot
    - goosefem
  run:
    - python

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tdegeus/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Spring-block friction model.
  description: Spring-block friction model.
  doc_url: https://tdegeus.github.io/{{ name }}
  dev_url: https://github.com/tdegeus/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
